---
version: 2
jobs:
  build:
    working_directory: ~/commons-api
    docker:
      - image: circleci/ruby:2.7.0
        environment:
          PGHOST: otto.db.elephantsql.com
          PGUSER: commons_dev
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: <%= Rails.application.secrets[:database][:psql_username] %>
          POSTGRES_DB: <%= Rails.application.secrets[:database][:psql_db] %>
          POSTGRES_PASSWORD: <%= Rails.application.secrets[:database][:psql_password] %>
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: commons-api{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --full-index

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: commons-api{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run:
          name: Set up DB
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
          environment:
            DATABASE_URL: 'postgres://wzlkhiza:ClW_BOa_QWKKAJonHmdCBzx962LxCVsO@otto.db.elephantsql.com:5432/wzlkhiza'

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: rspec
